# Generated by Django 5.2.15 on 2026-08-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_github_username_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=39, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('org_role', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
