services:
  db:
    image: mysql:8.0
    container_name: dashdb-container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./server
    container_name: dashserver-container
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./client
    container_name: dashclient-container
    command: npm run dev -- --host
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
  
  cypress:
    image: cypress/included:13.6.0
    container_name: dashcypress-container
    depends_on:
      - frontend
    env_file:
      - .env
    working_dir: /e2e
    volumes:
      - ./client/cypress:/e2e/cypress
      - ./client/cypress.config.js:/e2e/cypress.config.js
    profiles:
      - testing

volumes:
  mysql_data: